# Generated by Django 3.2.16 on 2022-12-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_02', models.IntegerField()),
                ('sensor_04', models.IntegerField()),
                ('sensor_06', models.IntegerField()),
                ('sensor_10', models.IntegerField()),
                ('sensor_11', models.IntegerField()),
                ('sensor_12', models.IntegerField()),
                ('stat', models.CharField(max_length=30)),
            ],
        ),
    ]
